server:
  port: 9995

spring:
  application:
      name: api-gateway-service
  cloud: 
   gateway:
    discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true

    routes:
      - id: customer-microservice
        uri: lb://customer-microservice
        predicates:
          - Path=/customer-microservice/**
        filters: StripPrefix=2
      - id: credit-microservice
        uri: lb://credit-microservice
        predicates:
          - Path=/credit-microservice/**
        filters: StripPrefix=2
      - id: account-microservice
        uri: lb://account-microservice
        predicates:
          - Path=/account-microservice/**
        filters: StripPrefix=2
      - id: movement-microservice
        uri: lb://movement-microservice
        predicates:
          - Path=/movement-microservice/**
        filters: StripPrefix=2
      - id: representative_microservice
        uri: lb://representative-microservice
        predicates:
          - Path=/representative-microservice/**
        filters: StripPrefix=2
      - id: wallet_microservice
        uri: lb://wallet-microservice
        predicates:
          - Path=/wallet-microservice/**
        filters: StripPrefix=2
      - id: movement_wallet_microservice
        uri: lb://movement-wallet-microservice
        predicates:
          - Path=/movemente-wallet-microservice/**
        filters: StripPrefix=2
      - id: monedero_microservice
        uri: lb://monedero-microservice
        predicates:
          - Path=/monedero-microservice/**
        filters: StripPrefix=2
      - id: movement_monedero_microservice
        uri: lb://movement-coin-microservice
        predicates:
          - Path=/movement-coin-microservice/**
        filters: StripPrefix=2


eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka
      defaultZone: http://localhost:9999/eureka